# -*- coding: utf-8 -*-
"""first_order_circuits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_prJXLlZR0T-nBzrCG-0YNmKmaRicOns
"""

import numpy as np
import matplotlib.pyplot as plt

"""# Question 1: Dynamics of RC Circuits

Consider the circuit shown below where the switch closes at $t=0$.
[image went here but there was a bunch of garbage]

## Part a: Mathematical Modelling

What is the differential equation that models this circuit for t > 0?  Give the derivative as a function of the voltage.
"""

power_supply = 5 # Volts
r1 = 2 * 10**3 # Ohms
r2 = 5 * r1
cap = 1 * 10**-6 # Farads

req = 1 / ((1 / r1) + (1 / r2))

"""
    v_der(voltage)

Calculate the derivative of the voltage at a time based on its value at that time.
"""
def v_der(voltage):
    # your derivative goes here
    # for example, if the differential equation looks like dv/dt + (1/RC) v = 0
    # then you would isolate the derivative, and input the expression on the
    # other side of the equal sign e.g.
    # return -1/(RC) voltage
    # NOTE: you MUST include the `return` keyword or else nothing will be output
    # return "I DID NOT CHANGE THE OUTPUT" # <-- return the actual number
    return power_supply - (1 / (req * cap)) * voltage

"""## Part b: Initial Condition

What is the initial condition $V(t = 0)$ of the voltage across the capacitor?
"""

initial_voltage = 5 # your initial condition goes here

"""## Part c: Time Constant

What is the time constant τ of this circuit?
"""

time_constant_rc = req * cap # your time constant goes here

"""## Part d: Propagate

Calculate the voltage across the capacitor from t = 0 to t = 10 τ, where τ is the time constant of the RC circuit.
"""

"""
    euler(v_old, v_der, dt)

Produce the next value using the Euler method.
"""
def euler(v_old, v_der, dt):
    return v_old + v_der * dt

# DEFINE PARAMETERS

# define the time domain
time_step  = time_constant_rc / 10
start_time = 0.0
end_time   = 10.0 * time_constant_rc + time_step # add dt so that np.arange produces 10 tau
domain     = np.arange(start_time, end_time, time_step)

# allocate voltages and define initial value
voltage    = np.zeros(len(domain))
voltage[0] = initial_voltage

# propagate the initial value using the Euler method
for i in range(1, len(domain)):
    old_voltage = voltage[i - 1]
    old_voltage_der = v_der(old_voltage)
    voltage[i] = euler(old_voltage, old_voltage_der, time_step)

voltage

"""## Part e: Plot, Interpret, and Reflect

Plot the voltages you've calculated.  Interpret and reflect on whether or not the information communicated by the plot is consistent with your prediction.
"""

scaled_voltages = voltage / initial_voltage # `np.array`s allow for scaling
plt.plot(
    domain / time_constant_rc,
    scaled_voltages
);
plt.xlabel("$t/tau$");
plt.ylabel("$V/V_0$");

"""My prediction is that the potential on top plate of the capacitor increases slower and slower asymptotically approaching the same potential that's on the lower plate.  So, while the potential on the top plate _increases_, the **difference** between the voltages i.e. the voltage across the capacitor, decreases with time.  The plot above is consistent with this prediction as the calculated voltage across the capacitor exponentially decreases with time.

Additionally, the voltage across the capacitor reaches about 37% after a single time-constant has passed.  This rate continues throughout the domain.  The continued rate then allows the voltage to asymptotically approach zero as time goes to infinity.  This data is also consistent with my prediction and what the theory suggests.

# Question 2: Dynamics of RL Circuits

The questions that follow are the same as in the previous question.

Consider the circuit shown below where the switch closes at $t=0$.
[image went here but there was a bunch of garbage, again]

## Part a: Mathematical Modelling

What is the differential equation that models this circuit for t > 0?  Give the derivative as a function of the current.
"""

"""
    curr_der(voltage)

Calculate the derivative of the current at a time based on its value at that time.
"""
def curr_der(current):
    # your derivative goes here
    # NOTE: you MUST include the `return` keyword or else nothing will be output
    return "I DID NOT CHANGE THE OUTPUT" # <-- return the actual number

"""## Part b: Initial Condition

What is the initial condition $V(t = 0)$ of the voltage across the capacitor?
"""

initial_current = # your initial condition goes here

"""## Part c: Time Constant

What is the time constant τ of this circuit?
"""

time_constant_rl = # your time constant goes here

"""## Part d: Propagate

Calculate the voltage across the capacitor from t = 0 to t = 10 τ, where τ is the time constant of the RC circuit.
"""

# DEFINE PARAMETERS

# define the time domain
time_step  = 0.01
start_time = 0.0
end_time   = 10.0 * time_constant_rl + time_step # add dt so that np.arange produces 10 tau
domain     = np.arange(start_time,  end_time, time_step)

# allocate voltages and define initial value
current    = np.zeros(len(domain))
current[0] = initial_current

# propagate the initial value using the Euler method
for i in range(1, len(domain) + 1):
    old_current = current[i - 1]
    old_current_der = curr_der(old_current)
    current[i] = euler(old_current, old_current_der, time_step)

"""## Part e: Plot, Interpret, and Reflect

Plot the currents you've calculated.  Interpret and reflect on whether or not the information communicated by the plot is consistent with your prediction.
"""

scaled_currents = current / initial_current # `np.array`s allow for scaling
plt.plot(
    domain,
    current
);
plt.xlabel("$t/tau$");
plt.ylabel("$I/I_0$");

"""\[Interpret and reflect here\]"""